printWidth: 140
tabWidth: 4
endOfLine: auto # EOL is handled by Git via .gitattributes
useTabs: false
plugins:
    - "prettier-plugin-tailwindcss"
overrides:
  - files:
      - "*.js"
      - "*.ts"
    options:
      singleQuote: true
      bracketSpacing: true
      semi: true
      trailingComma: es5
      arrowParens: always
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
